version: ~> 1.0

os:
  - linux

language: node_js

cache:
  directories:
    - ~/.npm
    - node_modules
    - ~/.sonar/cache

addons:
  sonarcloud:
    organization: "javierbrea"
    branch:
      name: "$TRAVIS_CURRENT_BRANCH"

node_js:
  - "v10.20.1"
  - "v12.16.2"
  - "v14.0.0"

script:
  - npm run lint
  - npm run test:ci
  - npm run coveralls

jobs:
  include:
    - stage: sonar
      env: ALLOW_FAIL=1
      script:
        - npm run test:coverage
        - sonar-scanner -Dsonar.login=${SONAR_TOKEN};
      if: env(SONAR_TOKEN) IS present
    - stage: deploy
      script:
        - echo "Deploying"
      deploy:
        provider: npm
        edge: true
        email: "javier.brea@gmail.com"
        api_key: "$NPM_TOKEN"
        on:
          tags: true
        skip_cleanup: true
  allow_failures:
    - env: ALLOW_FAIL=1
